---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: {{ $.Values.catalogSource.name }}
  namespace: openshift-marketplace
spec:
  displayName: {{ $.Values.catalogSource.displayName }}
  publisher: Custom
  sourceType: grpc
  image: {{ $.Values.catalogSource.image }}
