kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: approve-install-plans
rules:
  - verbs:
      - get
      - watch
      - list
      - patch
    apiGroups:
      - operators.coreos.com
    resources:
      - installplans
