apiVersion: batch/v1
kind: Job
metadata:
  name: approve-install-plans
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      volumes:
      - name: auto-approve-script-volume
        configMap:
          name: auto-approve-script
      serviceAccountName: approve-install-plans
      containers:
      - name: ose-cli
        image: registry.redhat.io/openshift4/ose-cli
        volumeMounts:
          - mountPath: /scripts
            name: auto-approve-script-volume
        command:
        - /bin/sh
        - -c
        - |
          cat /scripts/auto-approve.sh
          sh /scripts/auto-approve.sh
      restartPolicy: Never
